# Generated by Django 6.0.3 on 2026-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_grupo", models.CharField(max_length=100)),
                (
                    "pessoas",
                    models.ManyToManyField(related_name="grupos", to="pessoas.pessoa"),
                ),
            ],
        ),
    ]
