# Generated by Django 6.0.3 on 2026-03-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tempoPreparo", models.DurationField()),
                ("nacionalidade", models.CharField(max_length=20)),
            ],
        ),
    ]
