# Generated by Django 6.0.3 on 2026-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("unidade", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="receita",
            name="tempoPreparo",
        ),
        migrations.AddField(
            model_name="receita",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receita",
            name="tempo_preparo",
            field=models.PositiveIntegerField(
                blank=True, help_text="Tempo em minutos", null=True
            ),
        ),
        migrations.AlterField(
            model_name="receita",
            name="nacionalidade",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="receita",
            name="ingredientes",
            field=models.ManyToManyField(
                related_name="receitas", to="receita.ingrediente"
            ),
        ),
        migrations.CreateModel(
            name="Utilizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "receitas_favoritadas",
                    models.ManyToManyField(
                        blank=True, related_name="utilizadores", to="receita.receita"
                    ),
                ),
            ],
        ),
    ]
