# Generated by Django 6.0.4 on 2026-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola_online", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="numero",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="curso",
            name="imagem",
            field=models.ImageField(upload_to="cursos/"),
        ),
    ]
