# Generated by Django 6.0.3 on 2026-03-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="escola",
            name="nivelEnsino",
        ),
        migrations.RemoveField(
            model_name="escola",
            name="telefone",
        ),
        migrations.AddField(
            model_name="escola",
            name="rua",
            field=models.CharField(default="Desconhecido", max_length=100),
        ),
        migrations.AlterField(
            model_name="escola",
            name="cidade",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="escola",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano_letivo", models.CharField(max_length=9)),
                (
                    "escola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turmas",
                        to="escola.escola",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("numero_escola", models.PositiveIntegerField(unique=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                ("leciona", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "turma",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professor",
                        to="escola.turma",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("numero_escola", models.PositiveIntegerField(unique=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alunos",
                        to="escola.turma",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
