# Generated by Django 6.0.4 on 2026-06-22 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habitat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
                ("descricao", models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Tipagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Treinador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
                ("cidade", models.CharField(max_length=30)),
                ("idade", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("numero_pokedex", models.PositiveIntegerField(unique=True)),
                ("altura", models.DecimalField(decimal_places=2, max_digits=4)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=4)),
                ("descricao", models.TextField(max_length=300)),
                (
                    "habitats",
                    models.ManyToManyField(
                        related_name="pokemons", to="pokemonAPI.habitat"
                    ),
                ),
                (
                    "tipagens",
                    models.ManyToManyField(
                        related_name="pokemons", to="pokemonAPI.tipagem"
                    ),
                ),
                (
                    "treinador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pokemons",
                        to="pokemonAPI.treinador",
                    ),
                ),
            ],
        ),
    ]
