# Generated by Django 6.0.4 on 2026-07-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemonAPI", "0002_alter_pokemon_treinador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="altura",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="peso",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
