# Generated by Django 6.0.3 on 2026-03-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ginasio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Treinador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "especialidade",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="ginasio",
            name="rua",
            field=models.CharField(default="Desconhecido", max_length=100),
        ),
        migrations.AlterField(
            model_name="ginasio",
            name="cidade",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ginasio",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="SessaoTreino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "ginasio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessoes_ginasios",
                        to="ginasio.ginasio",
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessoes_membros",
                        to="ginasio.membro",
                    ),
                ),
                (
                    "treinador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessoes_treinadores",
                        to="ginasio.treinador",
                    ),
                ),
            ],
        ),
    ]
