# Generated by Django 6.0.3 on 2026-03-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AplicacaoDoQuizz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=40)),
                ("quantPerguntas", models.PositiveIntegerField()),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
    ]
