# Generated by Django 6.0.3 on 2026-04-11 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("habilidade_adquirida", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("1", "Soft Skill"), ("2", "Hard Skill")],
                        default="1",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculdade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("max_capacidade_alunos", models.PositiveIntegerField()),
                ("data_inauguracao", models.DateField()),
                ("e_publica", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("certificado", models.ImageField(upload_to="certificados/")),
            ],
        ),
        migrations.CreateModel(
            name="Localizacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("data", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("nota", models.IntegerField()),
                ("prazo", models.DateField()),
                ("link_github", models.URLField()),
                ("link_video", models.URLField(blank=True, null=True)),
                ("imagem", models.ImageField(upload_to="projetos/")),
            ],
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_sala", models.CharField(max_length=5)),
                ("tem_computadores", models.BooleanField()),
                ("quantidade_cadeiras", models.PositiveIntegerField()),
                ("quantidade_mesas", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("logo", models.ImageField(upload_to="tecnologias/")),
                ("link_website_oficial", models.URLField()),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[
                            (1, "Nenhum"),
                            (2, "Baixo"),
                            (3, "Médio"),
                            (4, "Alto"),
                            (5, "Super Interessante"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("nota", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ects", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                ("objetivo_curso", models.TextField()),
                ("competencias_adquiridas", models.TextField()),
                ("destinatario", models.TextField()),
                ("ligacao_meio_empresarial", models.TextField()),
                ("oportunidade_carreira", models.TextField()),
                ("total_anos", models.PositiveIntegerField()),
                (
                    "faculdade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.faculdade",
                    ),
                ),
                (
                    "tfc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenciaturas",
                        to="portfolio.tfc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                ("numero_aluno", models.CharField(max_length=10, unique=True)),
                ("competencias", models.ManyToManyField(to="portfolio.competencia")),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenciatura_aluno",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="faculdade",
            name="localizacao",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="portfolio.localizacao"
            ),
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=15, null=True)),
                ("numero_professor", models.CharField(max_length=10, unique=True)),
                ("licenciaturas", models.ManyToManyField(to="portfolio.licenciatura")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="competencia",
            name="projetos",
            field=models.ManyToManyField(blank=True, to="portfolio.projeto"),
        ),
        migrations.AddField(
            model_name="faculdade",
            name="salas",
            field=models.ManyToManyField(to="portfolio.sala"),
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(to="portfolio.tecnologia"),
        ),
        migrations.AddField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ects", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                ("imagem", models.ImageField(upload_to="ucs/")),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
                ("professores", models.ManyToManyField(to="portfolio.professor")),
                (
                    "projetos",
                    models.ManyToManyField(related_name="ucs", to="portfolio.projeto"),
                ),
            ],
        ),
    ]
