# Generated by Django 6.0.4 on 2026-05-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competencia",
            name="projetos",
        ),
        migrations.RemoveField(
            model_name="competencia",
            name="tecnologias",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="competencias",
        ),
        migrations.DeleteModel(
            name="Formacao",
        ),
        migrations.RemoveField(
            model_name="faculdade",
            name="localizacao",
        ),
        migrations.RemoveField(
            model_name="faculdade",
            name="salas",
        ),
        migrations.RenameField(
            model_name="tfc",
            old_name="descricao",
            new_name="sumario",
        ),
        migrations.RenameField(
            model_name="tfc",
            old_name="nome",
            new_name="titulo",
        ),
        migrations.RemoveField(
            model_name="faculdade",
            name="e_publica",
        ),
        migrations.RemoveField(
            model_name="faculdade",
            name="max_capacidade_alunos",
        ),
        migrations.RemoveField(
            model_name="licenciatura",
            name="tfc",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="nota",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="prazo",
        ),
        migrations.RemoveField(
            model_name="tecnologia",
            name="nivel_interesse",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="nota",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="projetos",
        ),
        migrations.AddField(
            model_name="aluno",
            name="bio",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="aluno",
            name="foto_perfil",
            field=models.ImageField(null=True, upload_to="aluno/foto_perfil/"),
        ),
        migrations.AddField(
            model_name="faculdade",
            name="bairro",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="faculdade",
            name="cidade",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="faculdade",
            name="rua",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="projeto",
            name="ano_semestre",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="projeto",
            name="uc",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
        ),
        migrations.AddField(
            model_name="tfc",
            name="areas",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="autores",
            field=models.ManyToManyField(related_name="tfcs", to="portfolio.aluno"),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciatura",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tfcs",
                to="portfolio.licenciatura",
            ),
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_pdf",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.ManyToManyField(related_name="tfcs", to="portfolio.professor"),
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="rating",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(
                related_name="tfcs", to="portfolio.tecnologia"
            ),
        ),
        migrations.DeleteModel(
            name="Competencia",
        ),
        migrations.DeleteModel(
            name="Localizacao",
        ),
        migrations.DeleteModel(
            name="Sala",
        ),
    ]
