# Generated by Django 6.0.3 on 2026-07-05 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_competencia_formacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="correcao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="makingof",
            name="decisao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="makingof",
            name="erro",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="makingof",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.projeto",
            ),
        ),
        migrations.AddField(
            model_name="makingof",
            name="tecnologia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.tecnologia",
            ),
        ),
        migrations.AddField(
            model_name="makingof",
            name="unidade_curricular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.unidadecurricular",
            ),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="data",
            field=models.DateField(),
        ),
    ]
