# Generated by Django 6.0.7 on 2026-07-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_makingof_correcao_makingof_decisao_makingof_erro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
