# Generated by Django 6.0.7 on 2026-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_alter_tfc_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chave",
            field=models.CharField(max_length=600, null=True),
        ),
    ]
